version: '3.8'

services:

  postgres:
    image: postgres:${POSTGRES_DB_TAG}
    container_name: db_container
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/log/postgresql
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - postgres

  app:
    image: app_image
    container_name: app_container
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
     - '${PORT}:${PORT}'
    volumes:
     - ./src:/app/src/
    depends_on:
     - postgres
    networks:
      - postgres

volumes:
  data:
  logs:

networks:
  postgres:
    driver: bridge